### ISSUE TITLE
examples don't work

### ISSUE THREAD

**Issue by TheBenji** [Irrelon/ige#420]
It seems like lots of the examples don't work anymore.

For example 15.1-isoimages,
it loads and shows me something but I can't do nothing.
Probably due to the errors:

```
Uncaught TypeError: undefined is not a function IgeEngine.js:642
50Uncaught TypeError: undefined is not a function client.js:662
155Uncaught TypeError: undefined is not a function client.js:662
```

Also for 24.4-multiplayer-isometric-keyboard and 101-isoisland it shows the loading screen and afterwards just a black screen without any error messages.
A little weird is the server log though:

IGE _log_ [IgeNode] : Current working directory is: S:\www\games\ige
IGE _log_ [IgeNode] : Starting game server in path: S:\www\games\ige/./examples/
24.4-multiplayer-isometric-keyboard
IGE _log_ [IgeNode] : Checking module paths declared in: S:\www\games\ige/./exam
ples/24.4-multiplayer-isometric-keyboard/ServerConfig.js
IGE _log_ [IgeNode] : Module paths confirmed, including 3 module(s)...
IGE _log_ [IgeNode] : Module "ServerNetworkEvents" loaded from: "S:\www\games\ig
e/./examples/24.4-multiplayer-isometric-keyboard/./gameClasses/ServerNetworkEven
ts.js"
IGE _log_ [IgeNode] : Module "Character" loaded from: "S:\www\games\ige/./exampl
es/24.4-multiplayer-isometric-keyboard/./gameClasses/Character.js"
IGE _log_ [IgeNode] : Module "PlayerComponent" loaded from: "S:\www\games\ige/./
examples/24.4-multiplayer-isometric-keyboard/./gameClasses/PlayerComponent.js"

As you can see I'm on a windows machine currently and the paths looks slightly messed up, not sure if that works this ways. However it does load the modules.

Any Ideas?

**Comment by TheMaverickProgrammer** [comment]
Same issues on OSX 10.11

**Comment by Irrelon** [comment]
Can you try now? I think some assets were missing from the web site that the engine wanted to load in most of the examples.

**Comment by Irrelon** [comment]
BY the way my asset fix won't fix 15.1-isoimages... that example has been messed up by some errant code. Gonna take some time to fix I think.

**Comment by foobarbecue** [comment]
It would be really good to know which examples are working as expected, and which aren't.

It's very hard to learn with examples that are half-broken. The turret in 16.2 does not respond to mouse or keyboard, 5.1-ui shows no text, 50-shapes just shows two white squares (but maybe that's all it's supposed to do?). I really like the engine, and the lander game is absolutely brilliant but in order to learn, we either need comprehensive documentation or examples with descriptions of what they do.

@Irrelon , could you please go through and just make a list of which ones still actually work?

**Comment by foobarbecue** [comment]
running 17.2-network-socketio server gives me:

`C:\Users\aaron\ige\examples\17.2-network-socketio>node ..\..\..\ige\server\ige -g .
Executing IGE Under Node.js Version v7.10.0
------------------------------------------------------------------------------
* Isogenic Game Engine Server v1.6.0@2015-04-29.001                                          *
* (C)opyright 2012 Irrelon Software Limited                                  *
* http://www.isogenicengine.com                                              *
------------------------------------------------------------------------------
IGE *log* [IgeNode] : Starting pre-init process. IGE Game Server loading...
IGE *log* [IgeNode] : Current working directory is: C:\Users\aaron\ige\examples\17.2-network-socketio
IGE *log* [IgeNode] : Starting game server in path: C:\Users\aaron\ige\examples\17.2-network-socketio/.
IGE *log* [IgeNode] : Checking module paths declared in: C:\Users\aaron\ige\examples\17.2-network-socketio/./ServerConfig.js
IGE *log* [IgeNode] : Module paths confirmed, including 1 module(s)...
IGE *log* [IgeNode] : Module "ServerNetworkEvents" loaded from: "C:\Users\aaron\ige\examples\17.2-network-socketio/././gameClasses/ServerNetworkEvents.js"
------------------------------------------------------------------------------
* Powered by the Isogenic Game Engine v1.6.0@2015-04-29.001                  *
* (C)opyright 2017 Irrelon Software Limited                                  *
* http://www.isogenicengine.com                                              *
------------------------------------------------------------------------------
C:\Users\aaron\ige\server\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\Users\aaron\ige\server\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\aaron\ige\server\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:571:32)

`

**Comment by Irrelon** [comment]
@foobarbecue Hey ya. So I think that the version of IGE in the master / stable branch will not work with very new versions of Node.js - in fact it was tested against something super old like 0.12.x if I remember correctly. Things have moved on significantly since then for Node.js and I suspect that is where the incompatibility lies.

That said, I have been working on a new version of IGE with a simpler project structure (think AngularJS but without any bloat).

You can take a look at the latest version in the appCore branch of the IGE repo.
